### ISSUE TITLE
Is the source code for the pre-built images available?

### ISSUE THREAD

**Issue by gtaska** [Infineon/psoc6cm0p#1]
**Have you looked for an answer?** Yes.

**Question/Issue**:

I want to be able to build the prebuilt images locally so that I can, for example, change the location in flash that it runs out of. Is the source code that was used to make these prebuilt images available?

**Context**

PSoC6 CY8C624AAZI-S2D44, building with ModusToolbox 2.1

**Where did you expect to find the answer?**

This repository's main README.md file, or possibly in the component subdirectories.

**Comment by vmedcy** [comment]
Hello @gtaska, the source code of COMPONENT_CM0P_SLEEP prebuilt image is the same as seen at https://github.com/cypresssemiconductorco/mtb-example-psoc6-dual-cpu-empty-app/tree/release-v2.0.0/cm0p_app.

Make sure to build with CONFIG=Release to ensure it fits into the memory area.

**Comment by gtaska** [comment]
Thanks for that. Is there any plan on releasing the source code for the other images?

**Comment by rmbk19** [comment]
Hi @gtaska, 

Unfortunately, at the moment there is no plan on releasing the source code for other images but here are some pointers that might help you - 

- CM0P_CRYPTO is identical to crypto server snippet code from https://cypresssemiconductorco.github.io/mtb-pdl-cat1/pdl_api_reference_manual/html/group__group__crypto__cli__srv.html

- CM0P_BLESS can be implemented by following BLE quick start guide https://cypresssemiconductorco.github.io/bless/ble_api_reference_manual/html/page_ble_quick_start.html + reusing some publicly available BLE + CM0+ code examples from PSoC Creator.

Hope this helps, 

Regards, 
Rakshith
